### ISSUE TITLE
Seed de imágenes no funciona

### ISSUE THREAD

**Issue by lortega** [arnaldog/vocablia#2]
El seed no funciona correctamente; no agrega imágenes bien.

**Comment by arnaldog** [comment]
No lo hace en heroku pero en el local si
como puedo responderte estos comentarios directo en github?

2013/8/27 Luis Ortega notifications@github.com

> El seed no funciona correctamente; no agrega imágenes bien.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lortega/vocablia/issues/2
> .

## 

Arnaldo Gaspar Vejar.

**Comment by lortega** [comment]
Respondiste directo en Github...
